[book]
title = "After Sundown 1e"
authors = ["Frank Trollman", "Lokathor", "Radthemad"]
description = "A tabletop RPG in a world of monsters and horror."

[build]
build-dir = "docs"
create-missing = true

[output.html]
additional-css = ["custom.css"]
